stages:
  - preparation
  - standard-test

dev-standtest-preparation:
  stage: preparation
  image: node:10.17.0
  tags:
    - sdm2021group3-docker
  only:
    - /^feature\/.*$/
    - /^bugfix\/.*$/
    - /^test\/.*$/
    - merge_requests
  cache:
    key: "fe-$CI_COMMIT_REF_SLUG"
    paths:
      - node_modules/
    policy: pull-push
  script:
    - cd ./ && npm install --save-dev commitlint @commitlint/config-conventional

dev-commit-test:
  stage: standard-test
  image: node:10.17.0
  tags:
    - sdm2021group3-docker
  only:
    - /^feature\/.*$/
    - /^bugfix\/.*$/
    - /^test\/.*$/
    - merge_requests
  cache:
    key: "fe-$CI_COMMIT_REF_SLUG"
    paths:
      - node_modules/
    policy: pull
  script:
    - git fetch origin master
    - ./node_modules/.bin/commitlint --color --verbose --from=$(git rev-parse remotes/origin/master)
