version: "2.4"

networks:
   mll-frontend-net:
        name: mll-frontend-net

services:
    mll-frontend:
        image: node:10.17.0
        container_name: mll-frontend
        restart: always
        environment:
            - CHOKIDAR_USEPOLLING=true
            - REACT_APP_API_PROTOCOL=${REACT_APP_API_PROTOCOL}
            - REACT_APP_API_PORT=${REACT_APP_API_PORT}
        networks:
            - mll-frontend-net
        working_dir: /app
        command: ["sh", "-c", "npm install && \
            HTTPS=true \
            SSL_CRT_FILE=/localhost.crt \
            SSL_KEY_FILE=/localhost.key \
            npm run start"]
