version: "3.5"

services:
    mll-frontend:
        command: ["sh", "-c", "npm install && \
            npm run build && \
            npm install -g http-server && \
            http-server --ssl --cert /localhost.crt --key /localhost.key --port 3000 ./build"]
