version: "3.5"

services:
    mll-frontend:
        volumes:
            - ./app/build:/app/build:delegated
            - ./localhost.crt:/localhost.crt
            - ./localhost.key:/localhost.key
        command: ["sh", "-c", "npm install -g http-server && \
            http-server --ssl --cert /localhost.crt --key /localhost.key --port 3000 ./build/"]
