version: "3.5"

networks:
   mll-frontend-net:
        name: mll-frontend-net

services:
    mll-frontend:
        image: node:10.17.0
        container_name: mll-frontend
        restart: always
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
            - ./app:/app:delegated
        environment:
            - CHOKIDAR_USEPOLLING=true
        ports:
            - "3000:3000"
        networks:
            - mll-frontend-net
        working_dir: /app
        command: ["sh", "-c", "npm install && npm run start"]
