version: "2.4"

networks:
   mll-frontend-net:
        name: mll-frontend-net

services:
    mll-frontend:
        extends:
            file: docker-compose.base.yml
            service: mll-frontend
        volumes:
            - ./app:/app:delegated
            - ./localhost.crt:/localhost.crt:ro
            - ./localhost.key:/localhost.key:ro
        ports:
            - "${APP_PORT}:3000"
